[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.releaseCommands]]
command = "python manage.py migrate --noinput"

[[deploy.releaseCommands]]
command = "python manage.py collectstatic --noinput"

[[deploy.releaseCommands]]
command = "python manage.py shell -c \"from django.contrib.auth.models import User; import os; u=os.environ.get('DJANGO_SUPERUSER_USERNAME','admin'); e=os.environ.get('DJANGO_SUPERUSER_EMAIL','admin@clubreserva.com'); p=os.environ.get('DJANGO_SUPERUSER_PASSWORD','admin1234'); User.objects.filter(username=u).exists() or User.objects.create_superuser(u, e, p)\""
