# Generated by Django 5.2.8 on 2026-04-26 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Deportiva', 'Deportiva'), ('Acuática', 'Acuática'), ('Fitness', 'Fitness'), ('Relajación', 'Relajación')], default='Deportiva', max_length=50)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('mantenimiento', 'Mantenimiento'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('precio_hora', models.DecimalField(decimal_places=2, default=30.0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('Tenis', 'Tenis'), ('Natación', 'Natación'), ('Yoga', 'Yoga'), ('Fitness', 'Fitness'), ('Pádel', 'Pádel'), ('Otro', 'Otro')], default='Tenis', max_length=50)),
                ('calificacion_promedio', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_resenas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('ausente', 'Ausente')], default='disponible', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseHoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(default='Clase', max_length=150)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo_maximo', models.PositiveIntegerField(default=10)),
                ('inscritos', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(default='Todos', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='reservas.instalacion')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='reservas.instructor')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='cliente', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('pendiente', 'Pendiente')], default='confirmada', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cliente', to=settings.AUTH_USER_MODEL)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.instalacion')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.instructor')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
