# Generated by Django 5.2.8 on 2026-05-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='instructores/'),
        ),
    ]
