# Generated by Django 5.2.8 on 2026-05-05 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_instructor_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='tarifa_hora',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='ClaseCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo_maximo', models.PositiveIntegerField(default=10)),
                ('nivel', models.CharField(choices=[('Todos', 'Todos los niveles'), ('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Todos', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('precio_persona', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_compartidas', to='reservas.instalacion')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_compartidas', to='reservas.instructor')),
            ],
            options={
                'verbose_name': 'Clase Compartida',
                'verbose_name_plural': 'Clases Compartidas',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='reservas.clasecompartida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['fecha_inscripcion'],
                'unique_together': {('cliente', 'clase')},
            },
        ),
    ]
