# Generated by Django 5.2.8 on 2026-05-05 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_instructor_tarifa_hora_clasecompartida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llegada_tarde', 'Llegada Tarde'), ('salida_temprana', 'Salida Temprana')], max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='reservas.instructor')),
            ],
            options={
                'verbose_name': 'Alerta Administrativa',
                'verbose_name_plural': 'Alertas Administrativas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
